#!/bin/env python3

import gzip
import argparse
import os

def get_arguments():
    """function to return the paths to the input files"""

    parser = argparse.ArgumentParser(description="Generate a table of the gene positions used in MatrixEQTL")
    parser.add_argument("-g", "--gtf", required=True, type=str, help="GTF used during the HTSeq analysis")
    parser.add_argument("-c", "--counts", type=str, help="Counts file generated by HTSeq to only retain the sampled genes [optional]", default=None)
 
    args = parser.parse_args()
    gtf = args.gtf
    htseq_counts = args.counts


    # make sure input files exist
    assert os.path.isfile(gtf), f"Could not locate {gtf}"
    if htseq_counts != None:
        assert os.path.isfile(htseq_counts), f"Could not locate {htseq_counts}"

    return gtf, htseq_counts

def parse_htseqs_file(htseq_counts: str):
    """assuming a single column-ed file with sample names to retain"""

    fh = gzip.open(htseq_counts, "rt") if htseq_counts.endswith(".gz") else open(htseq_counts, 'r')

    genes = set()

    # assuming header is present
    first_line = True
    for line in fh:
        if first_line:
            first_line = False
        else:
            gene_id = line.split('\t')[0]
            genes.add(gene_id)

    fh.close()

    return genes

def get_gene_id(attribs: str):
    """get the gene id from a gene entry"""

    fields  = attribs.split(';')
    gene_id = "None" # default value

    for field in fields:
        subfield = field.split(' ')
        if subfield[0] == "gene_id":
            gene_id = subfield[1].strip('"')
            break

    return gene_id

def make_output_name(gtf: str):
    """helper function to create output name"""

    bname = os.path.basename(gtf)

    if bname.endswith(".gz"):
        extension = ".gtf.gz"
    else:
        extension = ".gtf"

    outfile = bname.replace(extension, "_genepos.tsv")

    return outfile


def get_gene_positions(gtf: str, genes: set):
    """parse through the gtf to get the gene positions"""

    outfile = make_output_name(gtf)

    fh = gzip.open(gtf, "rt") if gtf.endswith(".gz") else open(gtf, 'r')

    outfh = open(outfile, 'w')
    outfh.write("geneid\tchr\tleft\tright\n")

    if genes != None: # genes were supplied
        using_genes = True
    else:
        using_genes = False

    for line in fh:
        if (len(line) == 0 or line[0] == '#'):
            continue
        fields = line.split('\t')
        if fields[2].lower() == "gene":
            gene_id = get_gene_id(fields[8])
            if using_genes:
                if gene_id not in genes:
                    continue # skip these
            start = int(fields[3])
            end = int(fields[4])
            chrom = fields[0]

            # construct the output line
            outline = f"{gene_id}\t{chrom}\t{start}\t{end}\n"
            outfh.write(outline)

    fh.close()
    outfh.close()


def main():
    """entry point to the pipeline"""

    # get the inputs
    gtf, htseq_counts = get_arguments()

    # get genes if supplied
    if htseq_counts != None:
        genes = parse_htseqs_file(htseq_counts)
    else:
        genes = None
    
    # now to get the gene positions
    get_gene_positions(gtf, genes)

if __name__ == "__main__":
    main()