#!/bin/env python3

import gzip
import argparse
import os

def get_arguments() -> tuple[str, str]:
    """function to return the paths to the vcf file to reformat"""

    parser = argparse.ArgumentParser(description="Reorder the SNPs/Genotype Matrix based on gene expression counts column order")
    parser.add_argument("-s", "--snps", required=True, type=str, help="SNPsMatrix file")
    parser.add_argument("-c", "--counts", required=True, type=str, help="Normalized Counts table generated by edgeR")


    args = parser.parse_args()
    snps = args.snps
    cnts = args.counts

    # make sure input file exist
    assert os.path.isfile(snps), f"Could not locate {snps}"
    assert os.path.isfile(cnts), f"Could not locate {cnts}"

    return (snps, cnts)

def get_column_order(counts: str) -> list[str]:
    """get the ordered list samples based on column order"""

    fh      = gzip.open(counts, "rt") if counts.endswith(".gz") else open(counts, 'r')
    samples = []

    header  = fh.readline().strip()

    for sample in header.split('\t'):
        if (sample == ''):
            continue
        samples.append(sample)
    fh.close()

    return samples

def write_reorder(snps: str, samples: list[str]) -> None:
    """write out the reordered file"""

    fh   = open(snps, 'r')
    ofh  = open("Reordered.SNPMatrix.tsv", 'w')
    ckey = {} # column key for original ordering

    for line in fh:
        if (len(line) == 0):
            continue
        fields = line.strip().split('\t')
        if (len(ckey) == 0):
            for i in range(1, len(fields)):
                ckey[fields[i]] = i
            header = ["snpid"] + samples
            header = '\t'.join(header)
            ofh.write(header)
            ofh.write('\n')
        else:
            newline = [fields[0]]
            for sample in samples:
                newline.append(fields[ckey[sample]])
            newline = '\t'.join(newline)
            ofh.write(newline)
            ofh.write('\n')

    fh.close()
    ofh.close()

def main():
    """entry point to the little program"""

    # get the inputs
    snps, cnt = get_arguments()

    # get the samples
    samples = get_column_order(cnt)

    # now reorder
    write_reorder(snps, samples)

    # creatte output
if __name__ == "__main__":
    main()